name: Publish Extension

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags, e.g., v1.2.3
  workflow_dispatch:  # Allows manual trigger
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: npm install

      - name: Publish to Visual Studio Marketplace & Open VSX
        env:
          VSCE_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          OVSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
        run: |
          npx @vscode/vsce publish -p $VSCE_TOKEN
          npx ovsx publish -p $OVSX_TOKEN
